# Parameters for snakemake run

input_file: "/rds/project/rds-aFEMMKDjWlo/aalmeida/project_ecoevo/metamlst/input_paths.tsv" # Input TSV file with list of paired-end FASTQ files (1st column forward path, 2nd column reverse path)

output_dir: "/rds/project/rds-aFEMMKDjWlo/aalmeida/project_ecoevo/metamlst/raw" # Output directory to store MLST results

metamlst_dir: "/rds/project/rds-aFEMMKDjWlo/software/metamlst" # Directory where metamlst is installed
